RECURSIVE_LIMIT = 3
GRAPH_FILE_PREFIX = "graph_"
HEADLESS = True
NAV_TIMEOUT_MS = 15000
CLICK_DELAY_MS = 300
USE_SCREENSHOT_IN_FINGERPRINT = True
MIN_PREDICTION_CONFIDENCE = 0.25
DEDUP_BBOX_OVERLAP_THRESHOLD = 0.8